language: python
dist: trusty

python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - pypy

addons:
  apt:
    packages:
      - libfreetype6-dev
      - libjpeg8-dev
      - liblcms2-dev
      - libtiff5-dev
      - libwebp-dev
      - python-tk
      - tcl8.6-dev
      - tk8.6-dev
      - zlib1g-dev

script:
  - pip install Pillow==2.3.0
  - if [[ $TRAVIS_PYTHON_VERSION == 2.6 ]]; then pip install backports.shutil_get_terminal_size; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then pip install backports.shutil_get_terminal_size; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3.2 ]]; then pip install backports.shutil_get_terminal_size; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 'pypy' ]]; then pip install backports.shutil_get_terminal_size; fi
  - python -m doctest -v fabulous/*.py
  - python setup.py install
  - yes | fabulous-demo
  - pip install sphinx==1.2.2
  - pip install sphinxcontrib-programoutput
  - sphinx-build docs gh-pages

notifications:
  email: false
